apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "ciprojectdetails", "namespace": "", "kind": "DeploymentConfig"}]'
    name: ciprojectdetails-pipeline
   spec:
     source:
       git:
          ref: pipeline
          uri: https://github.com/abhijitrpanchal/ci_employee_project.git
       type: Git
     strategy:
       type: JenkinsPipeline
       jenkinsPipelineStrategy:
         jenkinsfilePath: Jenkinsfile
     triggers:
     - generic:
         secret: 
       type: Generic
	
